name: SetHomePlugin
version: '1.0-SNAPSHOT'
main: xyz.nikilite.sethomeplugin.SetHomePlugin
api-version: '1.21'
author: "Nikilite"
description: "simple plugin that allows players to set and teleport to their home!"
commands:
  sethome:
    description: Sets your home location
    usage: /sethome
  home:
    description: Teleports you to your home
    usage: /home
  delhome:
    description: Deletes your home location
    usage: /delhome